language: php
sudo: false
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly
matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: "nightly"

before_script:
  - rm composer.lock
  - composer install
script: 
    - composer lint
    - composer phpunit
